# Generated by Django 5.2.6 on 2026-08-06 19:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teammember_role_alter_teammember_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='join_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
